export const USER_NOTE_REQUEST = "USER_NOTE_REQUEST";
export const USER_NOTE_FAILURE = "USER_NOTE_FAILURE";

export const USERS_CREATE_NOTE_SUCCESS = "USERS_CREATE_NOTE_SUCCESS";
export const USERS_UPDATE_NOTE_SUCCESS = "USERS_UPDATE_NOTE_SUCCESS";
export const USERS_DELETE_NOTE_SUCCESS = "USERS_DELETE_NOTE_SUCCESS";
export const USERS_GET_NOTE_SUCCESS = "USERS_GET_NOTE_SUCCESS";

export const USERS_IN_PROGRESS_NOTE_SUCCESS = "USERS_IN_PROGRESS_NOTE_SUCCESS";
export const USERS_PUBLISHED_NOTE_SUCCESS = "USERS_PUBLISHED_NOTE_SUCCESS";

export const USER_DOWNLOAD_NOTE_SUCCESS = "USER_DOWNLOAD_NOTE_SUCCESS";

export const USER_BUYER_REQUEST_NOTE_SUCCESS = "USER_BUYER_REQUEST_NOTE_SUCCESS";
