export const ADMIN_NOTE_REQUEST = "ADMIN_NOTE_REQUEST";
export const ADMIN_NOTE_FAILURE = "ADMIN_NOTE_FAILURE";

export const ADMIN_GET_USER_NOTE_SUCCESS = "ADMIN_GET_USER_NOTE_SUCCESS";

export const ADMIN_GET_UNDER_REVIEW_NOTE_SUCCESS = "ADMIN_GET_UNDER_REVIEW_NOTE_SUCCESS";
export const ADMIN_GET_PUBLISHED_NOTE_SUCCESS = "ADMIN_GET_PUBLISHED_NOTE_SUCCESS";
export const ADMIN_GET_DOWNLOADED_NOTE_SUCCESS = "ADMIN_GET_DOWNLOADED_NOTE_SUCCESS";
export const ADMIN_GET_REJECTED_NOTE_SUCCESS = "ADMIN_GET_REJECTED_NOTE_SUCCESS";

export const ADMIN_IN_REVIEW_UPDATE_SUCCESS = "ADMIN_IN_REVIEW_UPDATE_SUCCESS";
export const ADMIN_APPROVE_UPDATE_SUCCESS = "ADMIN_APPROVE_UPDATE_SUCCESS";
export const ADMIN_REJECT_UPDATE_SUCCESS = "ADMIN_REJECT_UPDATE_SUCCESS";
