export const ALL_CATEGORIES_REQUEST = "ADMIN_ALL_CATEGORIES_REQUEST";
export const ALL_CATEGORIES_SUCCESS = "ADMIN_ALL_CATEGORIES_SUCCESS";
export const ALL_CATEGORIES_FAILURE = "ADMIN_ALL_CATEGORIES_FAILURE";

export const ADD_CATEGORY_REQUEST = "ADMIN_ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADMIN_ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADMIN_ADD_CATEGORY_FAILURE";

export const GET_CATEGORY_REQUEST = "ADMIN_GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "ADMIN_GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "ADMIN_GET_CATEGORY_FAILURE";

export const EDIT_CATEGORY_REQUEST = "ADMIN_EDIT_CATEGORY_REQUEST";
export const EDIT_CATEGORY_SUCCESS = "ADMIN_EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAILURE = "ADMIN_EDIT_CATEGORY_FAILURE";

export const DELETE_CATEGORY_REQUEST = "ADMIN_DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "ADMIN_DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "ADMIN_DELETE_CATEGORY_FAILURE";
