export const ALL_CATEGORIES_REQUEST = "ADMIN_ALL_CATEGORIES_REQUEST";
export const ALL_CATEGORIES_SUCCESS = "ADMIN_ALL_CATEGORIES_SUCCESS";
export const ALL_CATEGORIES_FAILURE = "ADMIN_ALL_CATEGORIES_FAILURE";
