export const CONFIG_REQUEST = "CONFIG_REQUEST";
export const CONFIG_FAILURE = "CONFIG_FAILURE";
export const USER_GET_COUNTRY_SUCCESS = "USER_GET_COUNTRY_SUCCESS";
export const USER_GET_CATEGORY_SUCCESS = "USER_GET_CATEGORY_SUCCESS";
export const USER_GET_NOTE_TYPE_SUCCESS = "USER_GET_NOTE_TYPE_SUCCESS";
export const ADMIN_GET_CONFIG_SUCCESS = "ADMIN_GET_CONFIG_SUCCESS";
export const ADMIN_UPDATE_CONFIG_SUCCESS = "ADMIN_UPDATE_CONFIG_SUCCESS";
