export const CONFIG_REQUEST = "CONFIG_REQUEST";
export const CONFIG_FAILURE = "CONFIG_FAILURE";
export const USER_GET_COUNTRY_SUCCESS = "USER_GET_COUNTRY_SUCCESS";
export const USER_GET_CATEGORY_SUCCESS = "USER_GET_CATEGORY_SUCCESS";
export const USER_GET_NOTE_TYPE_SUCCESS = "USER_GET_NOTE_TYPE_SUCCESS";
