export const PROFILE_REQUEST = "USERS_PROFILE_REQUEST";
export const USERS_GET_PROFILE_SUCCESS = "USERS_GET_PROFILE_SUCCESS";
export const USERS_UPDATE_PROFILE_SUCCESS = "USERS_UPDATE_PROFILE_SUCCESS";
export const PROFILE_FAILURE = "USERS_PROFILE_FAILURE";
